// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYbxfgaGSeimGvOLWLbYgen5Gsuxj2OIo',
    appId: '1:127839357682:web:f72fa774ce17088b9f9e6b',
    messagingSenderId: '127839357682',
    projectId: 'next-cart-9c3bb',
    authDomain: 'next-cart-9c3bb.firebaseapp.com',
    storageBucket: 'next-cart-9c3bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHJ9sh5_mc4nToikSlyw1t_vSkzsLs80I',
    appId: '1:127839357682:android:547fbded4d5612659f9e6b',
    messagingSenderId: '127839357682',
    projectId: 'next-cart-9c3bb',
    storageBucket: 'next-cart-9c3bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl3sWAVZS_QpDlDRzea0eX6RJNptOYhuo',
    appId: '1:127839357682:ios:d9a1c4b0a07aaf019f9e6b',
    messagingSenderId: '127839357682',
    projectId: 'next-cart-9c3bb',
    storageBucket: 'next-cart-9c3bb.firebasestorage.app',
    iosClientId: '127839357682-20spn4vh73mndedstrftqqohnullepr5.apps.googleusercontent.com',
    iosBundleId: 'com.codexia.nextCart',
  );
}
